name: notebook_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 22 * * 1"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: True

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "${{ matrix.python.version }}"
          environment-file: environment.yml
          activate-environment: tb5-env
          auto-activate-base: false
          mamba-version: "*"
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
          channel-priority: true

      - name: env_info
        run: |
          conda info
          conda list

      - name: Run notebooks
        run: |
          python -m pytest . --nbval-lax
